### ISSUE TITLE
Background process

### ISSUE THREAD

**Issue by AmirSG2** [Gust4Oliveira/Last.fm-Discord-Rich-Presence#1]
Is there any chance that you can update it to make it work in the background?, I like your version since is simple to run.  Thanks

**Comment by Gust4Oliveira** [comment]
I understand the inconvenience of starting the script every time you start your PC and having the cmd opened forever. 
I'll look for a solution for that.

**Comment by Gust4Oliveira** [comment]
Check the latest release, i added background support, still don't run automatically when you boot your device, but there's a solution for that on the [README.md ](https://github.com/Gust4Oliveira/Last.fm-Discord-Rich-Presence/blob/master/README.md).
