### ISSUE TITLE
Update the RPC Icon

### ISSUE THREAD

**Issue by ViviNoSmol** [Gust4Oliveira/Last.fm-Discord-Rich-Presence#10]
Discord now accepts using RPC icons to a alternative server, this can allow to put (almost) every album cover posible from the last.fm servers. If the project its still alive, this could be awesome!

**Comment by tetrachan** [comment]
I added this in my current PR!
![image](https://user-images.githubusercontent.com/22358117/180354837-23e0b763-bded-4eca-9e64-9e8c1385613e.png)

Check it out/test it here #12
