### ISSUE TITLE
Connection problem at web service, retrying connection in

### ISSUE THREAD

**Issue by viczzz** [Gust4Oliveira/Last.fm-Discord-Rich-Presence#17]
title, am i have to change the api key and api key secret by creating my own api account on lastfm?

**Comment by Gust4Oliveira** [comment]
Hi, no that's not necessary, the source code already has last.fm and discord application tokens that authorize the use of their APIs. Check the latest release, maybe will solve your issue. If nothing changes open a new issue please.
