### ISSUE TITLE
Randomly stops displaying after a while

### ISSUE THREAD

**Issue by Fluttrr** [Gust4Oliveira/Last.fm-Discord-Rich-Presence#4]
I've been using this for a few weeks now and I notice that after a little while, it just stops updating my status.

Sometimes it just stops on the last song I was listening and it'll say I'm listening to one song forever and won't update, other times it just won't update my status when I start playing something, even though last.fm is saying it's scrobbling.

This is always fixed by restarting the program. If I can provide any logs or something, please let me know

**Comment by Gust4Oliveira** [comment]
Alright, i'll use the script in the next days for an extended time to try reproduce the issue, find out what is making it happen and fix it. 
Thanks for reporting.

**Comment by jscott5811** [comment]
Hi there, I am having this bug too. I usually have to restart the program to fix it. Is there a way for it to automatically restart the application every so often?

**Comment by Gust4Oliveira** [comment]
Hey there, i notice that some local and on last.fm servers connection instabilities was the trigger to this problem that often in a while the thread that handles communication crash. I've made some treatment on the lastest release (v.1.1.1) so the app keep himself running and trying to connect again if a connection problem happens. I'll check again when i have some time free, and i'll also look for a way that the app detects when the thread crashes and restart it self, it would solve this and others connection problems from the lastfm library. 

Answering your question, yes, you can set the application that run it self and restart it self often in a while using Windows Task Scheduler, but i think that you will have problems with the system tray integration, but you can try.
